name: Cypress Tests

on:
  pull_request:
    branches: [ main, AlperenBranch, MesutBranch ]
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      # To prevent cancellation of other matrix jobs if one fails
      fail-fast: false
      matrix:
        # Configure browsers to run tests in parallel
        browsers: [chrome, firefox]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Verify Cypress
        run: npx cypress verify
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browsers }}
          headed: false
          record: false
          # For running Cypress tests in parallel
          # Uncomment the following line if you have a Cypress Dashboard account
          # parallel: true
        env:
          # Add any environment variables your application needs here
          CYPRESS_BASE_URL: http://localhost:3000
          
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browsers }}
          path: cypress/screenshots
          if-no-files-found: ignore
          
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-${{ matrix.browsers }}
          path: cypress/videos
          if-no-files-found: ignore